# BE service used by end user

kind: Service
apiVersion: v1
metadata:
  name: basic-be
  labels:
    app.kubernetes.io/name: doris-cluster
    app.kubernetes.io/instance: basic
    app.kubernetes.io/component: be
    app.kubernetes.io/managed-by: doris-operator
spec:
  ports:
    - name: webserver-port
      port: 8040
  type: ClusterIP

---
# BE service used by peer

kind: Service
apiVersion: v1
metadata:
  name: basic-be-peer
  labels:
    app.kubernetes.io/name: doris-cluster
    app.kubernetes.io/instance: basic
    app.kubernetes.io/component: be
    app.kubernetes.io/managed-by: doris-operator
spec:
  ports:
    - name: heartbeat-service-port
      port: 9050
    - name: be-port
      port: 9060
    - name: brpc-port
      port: 8060
  type: ClusterIP


---
# BE stateful set

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: basic-be
  labels:
    app.kubernetes.io/name: doris-cluster
    app.kubernetes.io/instance: basic
    app.kubernetes.io/component: be
    app.kubernetes.io/managed-by: doris-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: doris-cluster
      app.kubernetes.io/instance: basic
      app.kubernetes.io/component: be
      app.kubernetes.io/managed-by: doris-operator
  serviceName: basic-be-peer
  replicas: 3

  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: be-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        volumeMode: Filesystem
        storageClassName: local

  template:
    metadata:
      labels:
        app.kubernetes.io/name: doris-cluster
        app.kubernetes.io/instance: basic
        app.kubernetes.io/component: be
        app.kubernetes.io/managed-by: doris-operator
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8040'
        prometheus.io/scrape: 'true'
    spec:
      volumes:
        - name: conf
          configMap:
            name: basic-be-config
        - name: be-log
          emptyDir: { }
      containers:
        - name: be
          image: 'apache/doris-be:1.2.3'
          resources:
            requests:
              cpu: '4'
              memory: 8Gi
          ports:
            - name: webserver-port
              containerPort: 8040
            - name: brpc-port
              containerPort: 8060
            - name: heartbeat-service-port
              containerPort: 9050
            - name: be-port
              containerPort: 9060
          env:
            - name: FE_SVC
              value: basic-fe
            - name: FE_QUERY_PORT
              value: '9030'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ACC_USER
              valueFrom:
                secretKeyRef:
                  name: basic-opr-account
                  key: user
            - name: ACC_PWD
              valueFrom:
                secretKeyRef:
                  name: basic-opr-account
                  key: password
          volumeMounts:
            - name: conf
              mountPath: /opt/apache-doris/be/conf
            - name: be-storage
              mountPath: /opt/apache-doris/be/storage
            - name: be-log
              mountPath: /opt/apache-doris/be/log
          readinessProbe:
            tcpSocket:
              port: 9050
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3

---
# BE configmap

kind: ConfigMap
apiVersion: v1
metadata:
  name: basic-be-config
  labels:
    app.kubernetes.io/name: doris-cluster
    app.kubernetes.io/instance: basic
    app.kubernetes.io/component: be
    app.kubernetes.io/managed-by: doris-operator
data:
  be.conf: |
    sys_log_level = INFO
    be_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060