# Broker service used by peer

kind: Service
apiVersion: v1
metadata:
  name: basic-broker-peer
  labels:
    app.kubernetes.io/name: doris-cluster
    app.kubernetes.io/instance: basic
    app.kubernetes.io/component: broker
    app.kubernetes.io/managed-by: doris-operator
spec:
  ports:
    - name: broker-ipc-port
      port: 8000
  type: ClusterIP

---
# Broker stateful set

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: basic-broker
  labels:
    app.kubernetes.io/name: doris-cluster
    app.kubernetes.io/instance: basic
    app.kubernetes.io/component: broker
    app.kubernetes.io/managed-by: doris-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: doris-cluster
      app.kubernetes.io/instance: basic
      app.kubernetes.io/component: broker
      app.kubernetes.io/managed-by: doris-operator
  serviceName: basic-broker-peer
  replicas: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: doris-cluster
        app.kubernetes.io/instance: basic
        app.kubernetes.io/component: broker
        app.kubernetes.io/managed-by: doris-operator
    spec:
      volumes:
        - name: conf
          configMap:
            name: basic-broker-config
      containers:
        - name: broker
          image: 'apache/doris-broker:1.2.3'
          resources:
            requests:
              cpu: '2'
              memory: 4Gi
          ports:
            - name: broker-ipc-port
              containerPort: 8000
          env:
            - name: FE_SVC
              value: basic-fe
            - name: FE_QUERY_PORT
              value: '9030'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ACC_USER
              valueFrom:
                secretKeyRef:
                  name: basic-opr-account
                  key: user
            - name: ACC_PWD
              valueFrom:
                secretKeyRef:
                  name: basic-opr-account
                  key: password
          volumeMounts:
            - name: conf
              mountPath: /opt/apache-doris/broker/conf
          readinessProbe:
            tcpSocket:
              port: 8000
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3

---
# CN configmap

kind: ConfigMap
apiVersion: v1
metadata:
  name: basic-broker-config
  labels:
    app.kubernetes.io/name: doris-cluster
    app.kubernetes.io/instance: basic
    app.kubernetes.io/component: broker
    app.kubernetes.io/managed-by: doris-operator
data:
  apache_hdfs_broker.conf: |
    broker_ipc_port = 8000
    client_expire_seconds = 3600
  log4j.properties: |
    log4j.rootLogger=debug,stdout,D
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.Target=System.out
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%-5p] %d{yyyy-MM-dd HH:mm:ss,SSS} method:%l%n%m%n
    log4j.appender.D=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.D.File=${BROKER_LOG_DIR}/apache_hdfs_broker.log
    log4j.appender.D.Append=true
    log4j.appender.D.Threshold=INFO
    log4j.appender.D.layout=org.apache.log4j.PatternLayout
    log4j.appender.D.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss}  [ %t:%r ] - [ %p ]  %m%n